### ISSUE TITLE
BeebFPGA+Music5000 = Soft Synth.

### ISSUE THREAD

**Issue by afarlie** [hoglet67/BeebFpga#1]
Assuming you are able to add the Music 5000 FPGA to this design, you'd have a rather versatile soft synth.

(Aside:  You also have a B-Em repository, but no way to raise issues on it, Will you consider adding Music 5000 support to your version of B-Em?)

**Comment by hoglet67** [comment]
Music 5000 had already been added to this.

As far as B-Em is concerned, I don't think I have the skills to do that.

**Comment by afarlie** [comment]
Re B-Em Do you know who might? (Beech seems to be dead:( )

**Comment by hoglet67** [comment]
OK, maybe I could be persuaded to have a go!

The Beech source code is GPL, and did get picked up by archive.org:
https://web.archive.org/web/*/http://darrenizzard.com/beechdownloads/Beech-src.zip

Are you a member on Stardot? That's mostly where I hang out. If not, I would definitely recommend signing up. Maybe we could continue the discussion over there?

Dave

**Comment by afarlie** [comment]
I am on Stardot,  the other issue is that whilst B-Em can still run on XP,  Beech needs Windows 7 or above.(I'm still on XP)..

**Comment by hoglet67** [comment]
OK, I've had a stab at this, and it's mostly working.

There is a new item on the sound menu to enable it.

Also, make sure to disable internal sound filter, as it clobbers all the bass.

Sound quality could possibly by improved, as I'm having to down-sample from Music 5000's 46.875KHz stereo to B-Em's 31.250KHz mono.

I'll maybe start a thread on stardot and you can let me know there how you get on.

Dave

**Comment by hoglet67** [comment]
Here's the stardot thread:
http://stardot.org.uk/forums/viewtopic.php?f=4&t=11983
