### ISSUE TITLE
Beebs core does not read/mout the MMB file

### ISSUE THREAD

**Issue by theshinyknight** [hoglet67/BeebFpga#11]
Hi,
I followed the instructions to set up the Beebs MMB file, which is in the root of the SD card (tried with FAT16 and FAT32), but the result is that the core can't see the drive.

When switching to the drive I get an error saying that there is no drive. This is on a Next device. The file was copied first, after formatting, then all the other files for the Next distro were copied on it, as per instructions. Is there any other steps to perform, that was not mentioned on the instructions? Thanks

**Comment by hoglet67** [comment]
Can you post a photo / screen shot of the actual error?

**Comment by hoglet67** [comment]
Closing as original posted has not responded with further information.
