### ISSUE TITLE
Zalaga crash?

### ISSUE THREAD

**Issue by sharpie7** [hoglet67/BeebFpga#13]
A "while your in there" thing. On my port Zalaga  from [BEEB.MMB File v1.02 for MicroSPI.](http://www.retroclinic.com/docs/BEEBMMB.zip) crashes during play. I would be interested if the same thing happens on the upstream version.

**Comment by hoglet67** [comment]
That's because it uses one of the 6502 illegal opcodes, which isn't present on the 65C02 core that you are probably using by default..

If you only care about a model B, then set UseT65Core to true and UseAlanDCore to false, then you should find Zalaga works fine.

**Comment by sharpie7** [comment]
Doh! Never thought about it using illegal opcodes!

**Comment by sharpie7** [comment]
This might all be useless to you, but I thought it was worth writing up just in case.

I tried to build my project using the T65 core to test Zalaga with a 6502. Unfortunately the T65 core causes Quartus to crash doing the build. I therefore added the original PeterW 6502 from FPGA64 to the project and build with that. It is supposed to implement the illegal 6502 instructions.

It produces a very odd effect. Zalaga runs, but with long pauses and lots of screen corruption. A couple of other common BBC games I tried worked fine.

**Comment by hoglet67** [comment]
What version of Quartus are you using?

I have a Cyclone II board (a DE1) and so I have to use 13.1.

It builds/runs fine with this version.

Is there any warning/error associated with the crash that indicates the source of the problem?

There was an interested thread on T65/Zalaga here:
https://stardot.org.uk/forums/viewtopic.php?t=20350

**Comment by sharpie7** [comment]
Thanks. Here's a odd thing. Previously the compile process was crashing during the layout/optimization phase somewhere. But with a few changes in aparently unrelated areas it now compiles with the T65, Obviously whatever corner case was causing the crash is no longer there.

With T65 in then Zalaga does work fine.

For future reference I am using Quartus 17.0.2 SJ Lite.

**Comment by hoglet67** [comment]
I'll close this issue then.
