### ISSUE TITLE
Cursor visible on Arcadians (Acornsoft)

### ISSUE THREAD

**Issue by sharpie7** [hoglet67/BeebFpga#15]
Hi - Same background as before - testing from the Retroclinic pack on my MiSTer port. Let me know if you can't reproduce on your platforms.

On Arcadians (Acornsoft) the cursor is visible in game and on the high score page.

**Comment by hoglet67** [comment]
That's now fixed.

**Comment by sharpie7** [comment]
Thanks. Nice catch.
