### ISSUE TITLE
Keyboard not responsive on Mr EE (Micropower)

### ISSUE THREAD

**Issue by sharpie7** [hoglet67/BeebFpga#16]
Hi - Same background as before - testing from the Retroclinic pack on my MiSTer port. Let me know if you can't reproduce on your platforms.

On Mr EE (Micropower) the keyboard is not responsive in the game (except for the "P" key for pause). Various keys seem to be treated as if they were continually pressed.

**Comment by hoglet67** [comment]
I don't seem to be able to reproduce this one...

Is there any chance on your setup is has switched to joystick input?

**Comment by sharpie7** [comment]
Yep. Pretty sure it's on my end somewhere. I'll investigate. Might be expecting joystick input as you suggest.

(actually just realized what it probably is, I haven't put anything in the joystick code yet. I wonder if it might read the unconnected input as a joystick fire button pressed).
