### ISSUE TITLE
Circus Hang

### ISSUE THREAD

**Issue by sharpie7** [hoglet67/BeebFpga#19]
Spilling over from *.

Retrogames Circus from https://stardot.org.uk/forums/viewtopic.php?p=288472#p288472 is hanging for me after coin insert. I suspect it' a problem on my port, but would be interested to know how it behaves on your platforms.

**Comment by hoglet67** [comment]
I don't get a hang after the coin inserted, and the game seems to start normally but there are a couple of issues:

1. There doesn't seem to be a keyboard only option
2. It seems to requires a truly analog joystick. With a digital joystick you can only position the seesaw in three places.

It's the same on a real Model B.

Maybe Tricky can confirm this is all as expected?

Dave

**Comment by sharpie7** [comment]
Behaviour is confirmed on the *. forum. We're good!

**Comment by richard-broadhurst** [comment]
Sorry, Circus is a paddle game and running the original arcade ROM, so analogue only.
It could have digital controls, but the game would probably be unplayable!
