### ISSUE TITLE
Mode 7 cursor alignment

### ISSUE THREAD

**Issue by sharpie7** [hoglet67/BeebFpga#20]
Hi Again

Question to see whether this is in my port or your original. In Mode 7 the cursor is about 1 or 2 pixels left of where it should be in my MiSTer port. Do you see the same thing?

Do you know where the cursor alignment between the CRTC and the teletext chip is controlled?

Thanks

**Comment by hoglet67** [comment]
On BeebFPGA with SCART output it seems identical to a real Model B.

This is what I'm getting:
![IMG_2415](https://user-images.githubusercontent.com/1951463/158979369-05229027-a31d-434a-ba94-f7fd805434af.JPG)

**Comment by hoglet67** [comment]
The course cursor alignment is controlled by R8 of the 6845 (0, 1 or 2 characters)

The pixel level cursot alignment is just whatever delays there are through the Video Processor

I'm building with IncludeVideoNuLA = true (and have been for a long time)

Which Video Processor are you using?

It's possible this issue only exists with the original Video Processor implementation.

**Comment by hoglet67** [comment]
Indeed, this is only an issue with the original Video Processor implementation (IncludeVideoNuLA = false).
![IMG_2418](https://user-images.githubusercontent.com/1951463/158984464-f1159403-3192-40e5-879c-03f3f0c055a9.JPG)

This is now fixed.
